### ISSUE TITLE
Why prevent following parent links when sub menus set to true

### ISSUE THREAD

**Issue by bebaps** [factor1/nifty-nav#19]
By default, `subMenuParentLink` is `false`, but why is this the case? A parent link in a menu is still a valid link, and the user expects this to be followed if they click on it. I understand if this was implemented to make it easier for the sub-menu functionality to work, for example 

```
niftyNav({
  subMenus: true,
  subMenuParentLink: true,
});
```

leads to behavior where the link is followed _and_ the sub menu will toggle open.

This functionality may need to be updated to allow for both following parent links and toggling sub menus independently.

**Comment by erwstout** [comment]
I'm not sure I'm following your question/concern.

By default its false, so that when clicking/tapping on the item the submenu opens and doesn't follow the link. In a lot of the navigation patterns we deal with, even the desktop counterpart, the top level item is usually just a `#` or no link, so preventing default on them stops it from jumping to the top of the page, etc. 

> A parent link in a menu is still a valid link, and the user expects this to be followed if they click on it.

I think it depends, really. And this ties into the design as well. If the design calls for a `+` or icon that indicates children, a user wouldn't think that.

When it comes to having a parent item that links, and then say a `+` that can be clicked and expanded, my personal feeling is that its bad UX and complicated for the user. I know I get frustrated when I _want_ to open the menu, but clicking the nav item takes me to a page and only clicking the `+` toggles. I don't know how @mattada feels about that - but I know we've only done that once or twice and it was because the client insisted on it. I don't think we would ever internally do a UX/UI pattern like that.

Let me know if I didn't cover what your thought process was.

**Comment by mattada** [comment]
Im a fan of preventing the parent from linking. We almost always set the first item in the sub to be the same in this case. 

About us (/about)
-- Our Story (/about)
-- Our staff (/about/staff)
-- Our history (/about/history)

So by being smart about the way we manage content and client expectations, we can get away with preventing the parent from linking.

**Comment by erwstout** [comment]
Also, coming back to this, there is an option built in to allow the following of parent links. Per the docs: 

> subMenuParentLink controls if a parent menu navigation link should be followed when clicked. Default: false
